Нужно больше функций
htmlacademy-javascript/126027-keksobooking-24 pull request #2
Opened 2021-09-27 06:41 UTC by Hisime

2021-09-27 15:47 UTC, PolinaShneider requested changes

2021-09-27 15:47 UTC, PolinaShneider commented on js/main.js
> +  return randomNumber.toFixed(length);
`toFixed` возвращает строку, а тебе нужно число

2021-09-27 15:47 UTC, PolinaShneider commented on js/main.js
> +  const randomNumber = min + Math.random() * (max + 1 - min);
Реализация ок, но у тебя это не учтено. 

> Учтите, что диапазон может быть только положительный, включая ноль. А также придумайте, как функция должна вести себя, если передать значение «до» меньшее, чем значение «от», или равное ему.

Можешь возвращать что-то типа 'неверный аргумент' или пытаться прямо в функции починить условие (скажем, брать отрицательные числа по модулю или менять аргументы местами) — на твое усмотрение

2021-09-28 10:55 UTC, Hisime commented on js/main.js
> +  return randomNumber.toFixed(length);
исправила

2021-09-28 12:23 UTC, PolinaShneider commented on package-lock.json
> -  "version": "23.0.0",
А это откуда и зачем?

2021-09-28 12:25 UTC, PolinaShneider commented on js/main.js
> +const isInvalidFloat = (number) => number < 0 || !(typeof number === 'number') || Number.isNaN(number);
Проверки на тип number и isNaN уже избыточны. Это один из критериев: https://up.htmlacademy.ru/javascript/24/criteries#d13

Пользователь может быть не очень умным и ввести отрицательные числа (или перепутать их местами), но все же по заданию функция принимает именно число

2021-09-28 12:34 UTC, Hisime commented on package-lock.json
> -  "version": "23.0.0",
Это добавилось, когда сделала `npm i`

2021-09-28 12:44 UTC, PolinaShneider commented on package-lock.json
> -  "version": "23.0.0",
А, ок

2021-09-28 14:44 UTC, Hisime commented on js/main.js
> +const isInvalidFloat = (number) => number < 0 || !(typeof number === 'number') || Number.isNaN(number);
А проверку на целое число в getRandomInteger нужно оставлять?

2021-09-28 15:49 UTC, PolinaShneider commented on js/main.js
> +const isInvalidFloat = (number) => number < 0 || !(typeof number === 'number') || Number.isNaN(number);
В этой функции лучше оставить, да

2021-09-28 15:51 UTC, merged